
# Manual/cache entry accepted
accepted_lines = [
    "Entry accepted.",
    "Cache updated.",
    "Data verified.",
    "Stored successfully.",
    "Cache locked.",
    "Entry synced.",
    "Memory aligned.",
    "Accepted cleanly.",
    "Data stored.",
    "Sync complete.",
    "Cache active.",
    "Input confirmed.",
    "Validated and saved.",
    "Storage secured.",
    "Entry logged.",
    "Cache live.",
    "Saved to core.",
    "Entry stable.",
    "Accepted and sealed.",
]
# Cache entry rejected (pending)
rejected_pending_lines = [
    "Hold initiated.",
    "Pending review.",
    "Awaiting input.",
    "Decision queued.",
    "Flagged for check.",
    "Under validation.",
    "On standby.",
    "Paused for approval.",
    "Temp block set.",
    "Awaiting clearance.",
    "Review in queue.",
    "Hold active.",
    "Deferred for now.",
    "Cache idle — pending.",
    "Processing delay.",
    "Suspended.",
    "Validation paused.",
    "Status uncertain.",
    "In limbo.",
    "Decision pending.",
]

# Opening cache editor (data rejected)
open_editor_lines = [
    "Editor online.",
    "Cache editor ready.",
    "Opening workspace.",
    "Edit mode active.",
    "Manual mode engaged.",
    "Access granted.",
    "Editor booted.",
    "Console open.",
    "Modify cache now.",
    "Edit session live.",
    "Cache panel open.",
    "Editor initiated.",
    "Rejection review open.",
    "Data edit live.",
    "Manual override ready.",
    "Review console ready.",
    "Edit terminal online.",
    "Editor active.",
    "Ready to modify.",
    "Cache control open.",
]

# Cache entry removed
cache_removed_lines = [
    "Entry purged.",
    "Cache cleared.",
    "Data erased.",
    "Slot freed.",
    "Removal done.",
    "Cache wiped.",
    "Deleted cleanly.",
    "Trace removed.",
    "Memory flushed.",
    "Node cleared.",
    "Cache reset.",
    "Entry gone.",
    "Cleanup done.",
    "Erasure complete.",
    "Removed fully.",
    "Slot emptied.",
    "Data dropped.",
    "Cache nullified.",
    "Record deleted.",
    "Entry void.",
]

new_task_responses = [
    "On it, sir.",
    "Understood.",
    "Right away, sir.",
    "Affirmative.",
    "Processing now.",
    "Consider it done.",
    "Executing command.",
    "Task initiated.",
    "Working on it.",
    "As you wish, sir.",
    "Engaging sequence.",
    "Copy that.",
    "Command received.",
    "Moving ahead.",
    "Acknowledged.",
    "Activating process.",
    "At once, sir.",
    "Starting operation.",
    "Running task.",
    "Proceeding, sir."
]

# Jarvis responses for repeated tasks
repeat_task_responses = [
    "Already done, sir.",
    "Repeating the task.",
    "Running it again.",
    "Same command, sir.",
    "Reinitiating process.",
    "Doing it once more.",
    "Task already executed.",
    "Replaying operation.",
    "Duplicate task detected.",
    "Redoing previous task.",
    "Once again, sir.",
    "Re-executing command.",
    "Same task, different moment.",
    "You’ve said that before.",
    "Resuming previous order.",
    "Repeating protocol.",
    "Re-running sequence.",
    "Task repetition confirmed.",
    "As before, sir.",
    "Redo in progress."
]